### ISSUE TITLE
support for ABB GoFa robot

### ISSUE THREAD

**Issue by AnirbanSinhaRobotics** [rpiRobotics/abb_motion_program_exec#48] opened 2024-06-01 02:07 UTC
Does *abb_motion_program_exec* support ABB GoFa 15000 robot? Is there any document available that one follow to setup EGM on OmniCoreC30 controller to use *abb_motion_program_exec*?

Thank you in advance.

**Comment by johnwason** [comment] 2024-06-01 14:33
Only IRC5 is currently supported.

**Comment by AnirbanSinhaRobotics** [comment] 2024-06-02 23:31
Ok, thanks. Is there any plan to include OmniCoreC30 controller in the near future?

**Comment by johnwason** [comment] 2024-06-07 00:12
It should be possible but we do not have any OmniCore robots so it is not a high priority.

**Comment by johnwason** [comment] 2024-07-12 15:02
Closing as duplicate of #37 for OmniCore support.

**Closed by johnwason** 2024-07-12 15:02 UTC
